---
title: "Creating New Variables"
author: "Yuling"
date: "4/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Common variables to create
##Missingness indicators
##"Cutting up" quantitative variables
##Spplying transforms

#Creating sequences
##Sometimes you need an index for your data set
s1 <- seq(1, 10, by = 2); s1

s2 <- seq(1,10, length = 3); s2

x <- c(1, 3, 8, 25, 100); seq(along = x)


#subsetting variables
resData$nearMe = restData$neighborhood %in% c("Roland Park", "Homeland")
table(restData$nearMe)

restData$zipwrong = ifelse(restData$zipCode < 0, TRUE, FALSE)
table(restData$zipwrong, restData$zipCode < 0)


#Creating categorical variables (exp: break quantity of variable up into a categorical variable)
restData$zipGroups = cut(resData$zipCode, breaks = quantile(restData$zipCode))
table(restData$zipGroups)
table(resData$zipGroups, restData$zipCode)

#easier cutting
library(Hmisc)
restData$zipGroups = cut2(restData$zipCode, g = 4)
table(resData$zipGroups)


#creating factor variables
restData$zcf <- factor(restData$zipCode)
restData$zcf[1:10]


#levels of factor variables
yesno <- sample(c("yes", "no"), size = 10, replace = TRUE)
yesnofac <- factor(yesno, levels = c("yes", "no")) #by default, the lower alphabet charactor will be ordered first, we specify the order with "levels = "
relevel(yesnofac, ref = "yes") #order is possible to be releveled
as.numeric(yesnofac)  #change it to numeric

#mutate function
library(Hmisc), library(plyr)
restData2 <- mutate(restData, zipGroups = cut2(zipCode, g = 4))

#Common transforms
abs(x) #absolute values
sqrt(x) #square root
ceiling(x) #ceiling(3.475) is 4
floor(x) #floor(3.475) is 3
round(x, digits = n) #round(3.475, digits = 2) is 3.48
signif(x, digits = n) #signif(3.475, digits = 2) is 3.5
cos(x), sin(x)
log(x) #natureal logarithm
log2(x), log10(x)
exp(x) #exponentiating x

```

