---
title: "reading from mySQL"
author: "Yuling"
date: "3/23/2022"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Install RMySQL, results='hide', warning=FALSE}
install.packages("RMySQL", repos = "http://cran.us.r-project.org")
install.packages("DBI", repos = "http://cran.us.r-project.org")
library(DBI)
library(RMySQL)

```

```{r connecting and listing database,  results='hide', warning=FALSE}
ucscDb <- dbConnect(MySQL(), user = "genome",
                    host = "genome-mysql.cse.ucsc.edu")
result <- dbGetQuery(ucscDb, "show databases");dbDisconnect(ucscDb);
```
```{r connecting to hg19 and listing tables,  results='hide', warning=FALSE}
hg19 <- dbConnect(MySQL(), user = "genome", db = "hg19",
                  host = "genome-mysql.cse.ucsc.edu")
allTables <- dbListTables(hg19)
length(allTables)

allTables[1:5]
```
```{r get dimensions of a specific table,  results='hide', warning=FALSE}
dbListFields(hg19, "affyU133Plus2")
dbGetQuery(hg19, "select count(*) from affyU133Plus2")
```
```{r read from the table,  results='hide', warning=FALSE}
affyData <- dbReadTable(hg19, "affyU133Plus2")
head(affyData)
```

```{r select a specific subset, results='hide', warning=FALSE}
query <- dbSendQuery(hg19, "select * from affyU133Plus2 where misMatches between 1 and 3")
affyMis <- fetch(query); quantile(affyMis$misMatches)
affyMisSmall <- fetch(query, n = 10); dbClearResult(query)
dim(affyMisSmall)

#Don't forget to close the connection once done with data subtract
dbDisconnect(hg19)
```


```{r}
#RMySQL vignette: http://cran.r-project.org/web/packages/RMySQL/RMySQL.pdf
#List of commands: http://www.pantz.org/software/mysql/mysqlcommands.html
#blog post with summary of some other commands: http://www.r-bloggers.com/mysql-and-r/
```

